server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /auth/ {
        proxy_pass http://quiz-backend:8081/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://quiz-backend:8081/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
